### PR TITLE
Icon redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon was not good at all. It didn't convey the use of the app properly, the arrow wasn't visible, the dollar sign looks too generic.The color although it was using the palette in the [eOS HIG](https://elementary.io/docs/human-interface-guidelines#color) It doesn't follow the clear instructions on how the color should be used. Slate, silver, and black should be used minimally as primary color.

### CODE REVIEW

**Review by NathanBnm — APPROVED** [review]

**Comment by jeremyvaartjes** [comment]
I agree that the colours need to be improved. I'm not too sure how I feel about the icons provided, it looks a bit overwhelming.

I've put a possible variation here based on my original icon. Let me know if you have any thoughts on this.

subminder

**Comment by Fatih20** [comment]
Overwhelming how? There's no way to convey the meaning of your app without using some unique shapes and symbol. 

Furthermore, have you read the eOS HIG I've linked in the post? It specifically said how pictogram should be implemented. And again, people barely know if it's an arrow.

**Comment by jeremyvaartjes** [comment]
I have read the eOS HIG.

The overwhelming nature of your icon comes from the fact that you have a swirly arrow that has a drop-shadow making it look like a vortex.

I've installed your icon and at the "small" size setting in the dock, your arrow is less visible than it is in mine, not to mention that your $ symbol is less contrasting than I have it (as tested in Dan's "Harvey" app), which was my original intent with the colours in my original logo.

**Comment by NathanBnm** [comment]
I think this icon is too much like the new Mindi app from Torikul Habib

**Comment by Fatih20** [comment]
Because I also designed that icon.

**Comment by Fatih20** [comment]
> The overwhelming nature of your icon comes from the fact that you have a swirly arrow that has a drop-shadow making it look like a vortex.

But that's the point, the vertex is meant to represent confusing subscription that has no clear roots. 
I won't say that it's not overwhelming, but do you have an alternative to mine and yours? Because the arrow isn't visible. It could be whatever app that involves money. And furthermore, it could also be an app to exchange currency from both mine and your icon. So, perhaps we need a new concept altogether?

**Comment by NathanBnm** [comment]
> Because I also designed that icon.

Sure I know, but you can't apply the same style to different app icons according to what you said icons need to be unique and represent the app.

**Comment by Fatih20** [comment]
You're right. I based my redesign on the original icon which involves arrow and dollar sign. Maybe we need a new icon concept?

**Comment by NathanBnm** [comment]
The original icon suited me well

**Comment by Fatih20** [comment]
No. People can barely see that it's an arrow. In smaller size, the not-so-visible-arrow just become a mess of a pixel.

**Comment by NathanBnm** [comment]
I still prefer the new icon proposed by @jeremyvaartjes 'cause the icon you're actually trying to change is way to much like the Mindi app icon from @torikulhabib.

**Comment by Fatih20** [comment]
I know it's your project and whatnot, but do you realize how horrible your current icon is when you look at it side by side with other eOS icon in the appcenter site and in real life when the app is on the docks?

**Pull request closed without merging**
